export const SCHOOLS: Record<string, string> = {
  '104': 'Alta View Elementary',
  '103': 'Altara Elementary',
  '106': 'Bella Vista Elementary',
  '107': 'Brookwood Elementary',
  '108': 'Butler Elementary',
  '110': 'Canyon View Elementary',
  '112': 'Copperview Elementary',
  '116': 'Crescent Elementary',
  '120': 'Draper Elementary',
  '122': 'East Midvale Elementary',
  '123': 'East Sandy Elementary',
  '125': 'Glacier Hills Elementary',
  '130': 'Granite Elementary',
  '135': 'Lone Peak Elementary',
  '140': 'Midvale Elementary',
  '144': 'Midvalley Elementary',
  '143': 'Oak Hollow Elementary',
  '149': 'Oakdale Elementary',
  '155': 'Park Lane Elementary',
  '150': 'Peruvian Park Elementary',
  '154': 'Quail Hollow Elementary',
  '151': 'Ridgecrest Elementary',
  '156': 'Sandy Elementary',
  '158': 'Silver Mesa Elementary',
  '164': 'Sprucewood Elementary',
  '159': 'Sunrise Elementary',
  '174': 'Willow Canyon Elementary',
  '178': 'Willow Springs Elementary',
  '401': 'Albion Middle',
  '402': 'Butler Middle',
  '407': 'Draper Park Middle',
  '403': 'Eastmont Middle',
  '405': 'Indian Hills Middle',
  '404': 'Midvale Middle',
  '408': 'Mt. Jordan Middle',
  '410': 'Union Middle',
  '702': 'Alta High',
  '705': 'Brighton High',
  '711': 'Corner Canyon High',
  '706': 'Hillcrest High',
  '708': 'Jordan High',
  '750': 'Diamond Ridge',
  '955': 'High School Youth Academy',
  '740': 'CTEC',
  '981': 'Entrada/Community Ed',
  '180': 'Gold Miners Daughter',
  '810': 'Jordan Valley',
  '840': 'Canyons Transition Academy',
  '011': 'Board of Education',
  '021': 'External Affairs',
  '099': 'CSDtv Studio',
  '000': 'District Office',
  '0': 'District Office',
  '51': 'Canyons District Office',
}

export function getSchoolName(code: string | null | undefined): string {
  if (!code) return ''
  const name = SCHOOLS[code.toString()]
return name || code
}